FROM scratch

COPY bin/fillindexer /fillindexer

COPY docker-cfg/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

CMD ["/fillindexer", "redis:6379", "queue://pgordersfilled", "postgres", "postgres", "/run/secrets/postgress_password"]
