FROM corebuild

FROM scratch

COPY --from=corebuild /go/src/github.com/notegio/openrelay/bin/pooladmin /pooladmin

COPY --from=corebuild /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

CMD ["/pooladmin", "postgres://postgres@postgres", "/run/secrets/postgress_password", "redis:6379", "topic://released"]
