FROM golang:1.8 as corebuild

RUN mkdir -p /go/src/github.com/notegio/openrelay

WORKDIR /go/src/github.com/notegio/openrelay

COPY . .

RUN make clean bin

FROM scratch

COPY --from=corebuild /go/src/github.com/notegio/openrelay/bin/initialize /initialize

CMD ["/initialize"]
