FROM scratch

COPY bin/automigrate /automigrate

COPY docker-cfg/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

CMD ["/automigrate", "postgres", "postgres", "/run/secrets/postgress_password"]
