FROM scratch

COPY bin/allowancemonitor /allowancemonitor

CMD ["/allowancemonitor", "redis:6379", "ethnode:8545", "queue://newblocks", "queue://recordspend", "0x48bacb9266a570d521063ef5dd96e61686dbe788"]
